name = "civil-exam-drill"
compatibility_date = "2026-08-31"
pages_build_output_dir = "dist"
migrations_dir = "migrations"

[[d1_databases]]
binding = "DB"
database_name = "civil-exam-drill-db"
database_id = "3618e0cf-94ec-46fd-bce2-2f03d0eef7b7"
