PRAGMA foreign_keys = ON;

CREATE TABLE invite_codes (id INTEGER PRIMARY KEY AUTOINCREMENT, code_hash TEXT NOT NULL UNIQUE, label TEXT, enabled INTEGER NOT NULL DEFAULT 1 CHECK (enabled IN (0,1)), expires_at TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE users (id TEXT PRIMARY KEY, invite_code_id INTEGER NOT NULL, nickname TEXT NOT NULL CHECK(length(nickname) BETWEEN 1 AND 12), nickname_normalized TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'active' CHECK(status IN ('active','disabled')), created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, last_login_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(invite_code_id) REFERENCES invite_codes(id), UNIQUE(invite_code_id,nickname_normalized));
CREATE TABLE sessions (id TEXT PRIMARY KEY, user_id TEXT NOT NULL, token_hash TEXT NOT NULL UNIQUE, expires_at TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, last_seen_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
CREATE TABLE auth_attempts (id INTEGER PRIMARY KEY AUTOINCREMENT, client_key TEXT NOT NULL, succeeded INTEGER NOT NULL CHECK(succeeded IN (0,1)), created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX idx_auth_attempts_client_created ON auth_attempts(client_key,created_at DESC);
CREATE TABLE generated_questions (id TEXT PRIMARY KEY, user_id TEXT NOT NULL, topic_id TEXT NOT NULL, difficulty TEXT NOT NULL, template_id TEXT NOT NULL, template_version INTEGER NOT NULL, fingerprint TEXT NOT NULL, seed TEXT NOT NULL, stem TEXT NOT NULL, options_json TEXT NOT NULL, answer_index INTEGER NOT NULL CHECK(answer_index BETWEEN 0 AND 3), explanation TEXT NOT NULL, params_json TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, expires_at TEXT NOT NULL, FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
CREATE INDEX idx_questions_recent ON generated_questions(user_id,topic_id,difficulty,created_at DESC);
CREATE TABLE quiz_attempts (id TEXT PRIMARY KEY, user_id TEXT NOT NULL, question_id TEXT NOT NULL, selected_index INTEGER NOT NULL CHECK(selected_index BETWEEN 0 AND 3), correct INTEGER NOT NULL CHECK(correct IN (0,1)), duration_ms INTEGER NOT NULL CHECK(duration_ms >= 0), mastered INTEGER NOT NULL DEFAULT 0 CHECK(mastered IN (0,1)), idempotency_key TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE, FOREIGN KEY(question_id) REFERENCES generated_questions(id), UNIQUE(user_id,question_id), UNIQUE(user_id,idempotency_key));
CREATE TABLE schulte_results (id TEXT PRIMARY KEY, user_id TEXT NOT NULL, grid_size INTEGER NOT NULL CHECK(grid_size BETWEEN 2 AND 10), variant TEXT NOT NULL, duration_ms INTEGER NOT NULL CHECK(duration_ms > 0), errors INTEGER NOT NULL DEFAULT 0 CHECK(errors >= 0), idempotency_key TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE, UNIQUE(user_id,idempotency_key));
CREATE INDEX idx_quiz_attempts_user_created ON quiz_attempts(user_id,created_at DESC);
CREATE INDEX idx_schulte_user_created ON schulte_results(user_id,created_at DESC);
